<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260522000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create workout tracking schema for exercises, sessions, entries and sets.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, type VARCHAR(20) NOT NULL, muscle_groups JSON NOT NULL, notes TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE workout_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) DEFAULT NULL, session_date DATE NOT NULL, mood VARCHAR(30) DEFAULT NULL, notes TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE workout_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workout_session_id INT NOT NULL, exercise_id INT NOT NULL, order_index INT NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1B1F6A1A4E68BD73 ON workout_entry (workout_session_id)');
        $this->addSql('CREATE INDEX IDX_1B1F6A1A1A8E3F8E ON workout_entry (exercise_id)');
        $this->addSql('CREATE TABLE workout_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workout_entry_id INT NOT NULL, set_number INT NOT NULL, weight_kg DOUBLE PRECISION DEFAULT NULL, reps INT DEFAULT NULL, duration_seconds INT DEFAULT NULL, distance_meters DOUBLE PRECISION DEFAULT NULL, speed_kmh DOUBLE PRECISION DEFAULT NULL, incline DOUBLE PRECISION DEFAULT NULL, resistance_level INT DEFAULT NULL, calories INT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F99FE74D62A2F6C3 ON workout_set (workout_entry_id)');
        $this->addSql('ALTER TABLE workout_entry ADD CONSTRAINT FK_1B1F6A1A4E68BD73 FOREIGN KEY (workout_session_id) REFERENCES workout_session (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE workout_entry ADD CONSTRAINT FK_1B1F6A1A1A8E3F8E FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE workout_set ADD CONSTRAINT FK_F99FE74D62A2F6C3 FOREIGN KEY (workout_entry_id) REFERENCES workout_entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE workout_set DROP CONSTRAINT FK_F99FE74D62A2F6C3');
        $this->addSql('ALTER TABLE workout_entry DROP CONSTRAINT FK_1B1F6A1A4E68BD73');
        $this->addSql('ALTER TABLE workout_entry DROP CONSTRAINT FK_1B1F6A1A1A8E3F8E');
        $this->addSql('DROP TABLE workout_set');
        $this->addSql('DROP TABLE workout_entry');
        $this->addSql('DROP TABLE workout_session');
        $this->addSql('DROP TABLE exercise');
    }
}
